name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest
      - name: Android Test Report
          uses: asadmansr/android-test-report-action@v1.2.0
          if: ${{ always() }}

  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/*.apk